# Generated by Django 5.2.15 on 2026-07-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('ejercicios', '0001_initial'),
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre_snapshot', models.CharField(max_length=120)),
                ('objetivo_snapshot', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutinas_asignadas', to='alumnos.alumno')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'rutina asignada',
                'verbose_name_plural': 'rutinas asignadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RutinaAsignadaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ejercicio_nombre_snapshot', models.CharField(max_length=120)),
                ('ejercicio_video_snapshot', models.URLField(blank=True)),
                ('dia', models.PositiveSmallIntegerField(help_text='Día N de la rutina (1..dias_por_semana), no día de la semana.')),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden dentro del día.')),
                ('series', models.PositiveSmallIntegerField()),
                ('repeticiones', models.CharField(max_length=20)),
                ('descanso', models.CharField(blank=True, max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('rutina_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rutinas.rutinaasignada')),
            ],
            options={
                'verbose_name': 'item de rutina asignada',
                'verbose_name_plural': 'items de rutina asignada',
                'ordering': ['dia', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RutinaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('objetivo', models.CharField(max_length=120)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('dias_por_semana', models.PositiveSmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'plantilla de rutina',
                'verbose_name_plural': 'plantillas de rutina',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutinaPlantillaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('dia', models.PositiveSmallIntegerField(help_text='Día N de la rutina (1..dias_por_semana), no día de la semana.')),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden dentro del día.')),
                ('series', models.PositiveSmallIntegerField()),
                ('repeticiones', models.CharField(help_text='Notación libre: "10", "8-12", "AMRAP", etc.', max_length=20)),
                ('descanso', models.CharField(blank=True, help_text='Ej: "60s", "2 min".', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_plantilla', to='ejercicios.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rutinas.rutinaplantilla')),
            ],
            options={
                'verbose_name': 'item de plantilla',
                'verbose_name_plural': 'items de plantilla',
                'ordering': ['dia', 'orden'],
            },
        ),
    ]
