# Generated by Django 5.2.15 on 2026-07-27 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaasignadaitem',
            options={'ordering': ['semana', 'dia', 'orden'], 'verbose_name': 'item de rutina asignada', 'verbose_name_plural': 'items de rutina asignada'},
        ),
        migrations.AlterModelOptions(
            name='rutinaplantillaitem',
            options={'ordering': ['semana', 'dia', 'orden'], 'verbose_name': 'item de plantilla', 'verbose_name_plural': 'items de plantilla'},
        ),
        migrations.AddField(
            model_name='rutinaasignadaitem',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1, help_text='Semana del ciclo (1 a 4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='rutinaplantillaitem',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1, help_text='Semana del ciclo (1 a 4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
