# Generated by Django 5.2.15 on 2026-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_alter_rutinaasignadaitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaasignadaitem',
            name='rpe',
            field=models.CharField(blank=True, choices=[('mas_intenso', 'Podría hacer más intenso'), ('seguir_intensidad', 'Podría seguir con esta intensidad'), ('al_limite', 'Estoy al límite'), ('bajar_intensidad', 'Debería bajar la intensidad')], help_text='Cómo sintió el alumno la intensidad de este ejercicio esta semana. Lo carga el propio alumno desde su portal, no el staff. blank=True: recién se completa cuando el alumno lo califica.', max_length=20),
        ),
    ]
