# Generated by Django 5.2.15 on 2026-08-13 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_rutinaasignadaitem_rpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaAsignadaDiaCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('dia', models.PositiveSmallIntegerField()),
                ('semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('completado_en', models.DateTimeField(auto_now_add=True)),
                ('rutina_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_completados', to='rutinas.rutinaasignada')),
            ],
            options={
                'verbose_name': 'día completado',
                'verbose_name_plural': 'días completados',
                'unique_together': {('rutina_asignada', 'dia', 'semana')},
            },
        ),
    ]
