# Generated by Django 5.2.15 on 2026-08-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_rutinaasignadadiacompletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaasignadaitem',
            name='grupo_muscular_snapshot',
            field=models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('core', 'Core'), ('cardio', 'Cardio'), ('cuerpo_completo', 'Cuerpo completo')], help_text="Copiado de Ejercicio.grupo_muscular al momento de asignar la rutina, para poder agrupar la vista del alumno y el PDF sin depender de una FK viva. Vacío en asignaciones creadas antes de este campo (no se puede reconstruir retroactivo con confianza) -- ver rutinas/agrupacion.py, que bucketea esos casos bajo 'Sin grupo muscular' en vez de romper.", max_length=20),
        ),
        migrations.AddField(
            model_name='rutinaasignadaitem',
            name='kilos',
            field=models.CharField(blank=True, help_text='Notación libre: "20kg", "corporal", "15kg c/u", etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='rutinaplantillaitem',
            name='kilos',
            field=models.CharField(blank=True, help_text='Notación libre: "20kg", "corporal", "15kg c/u", etc.', max_length=30),
        ),
    ]
