# Generated by Django 5.2.15 on 2026-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_categoria_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaasignadaitem',
            name='bloque',
            field=models.CharField(blank=True, help_text='Código de superserie: "A1", "B2". Los ejercicios del mismo bloque se hacen juntos, uno atrás del otro.', max_length=10),
        ),
        migrations.AddField(
            model_name='rutinaasignadaitem',
            name='dia_nombre',
            field=models.CharField(blank=True, help_text='Nombre del día: "Tren superior · Core". Opcional.', max_length=80),
        ),
        migrations.AddField(
            model_name='rutinaplantillaitem',
            name='bloque',
            field=models.CharField(blank=True, help_text='Código de superserie: "A1", "B2". Los ejercicios del mismo bloque se hacen juntos, uno atrás del otro.', max_length=10),
        ),
        migrations.AddField(
            model_name='rutinaplantillaitem',
            name='dia_nombre',
            field=models.CharField(blank=True, help_text='Nombre del día: "Tren superior · Core". Opcional.', max_length=80),
        ),
    ]
