# Generated by Django 5.2.15 on 2026-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0008_bloque_y_dia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaasignadaitem',
            name='ejercicio_video_snapshot',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
