# Generated by Django 5.2.15 on 2026-08-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0009_alter_rutinaasignadaitem_ejercicio_video_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaasignada',
            options={'ordering': ['-fecha_inicio', '-id'], 'verbose_name': 'rutina asignada', 'verbose_name_plural': 'rutinas asignadas'},
        ),
    ]
