# Generated by Django 5.2.15 on 2026-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_actividad_fisica_previa_and_more'),
        ('rutinas', '0011_cerrar_rutinas_activas_duplicadas'),
        ('tenants', '0008_gimnasio_link_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaasignada',
            name='activa',
            field=models.BooleanField(default=True, help_text="Archivada a mano. NO significa 'la que ve el alumno' -- eso lo decide `vigente_de` por fecha."),
        ),
        migrations.AlterField(
            model_name='rutinaasignada',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Cierre MANUAL, opcional. La vigencia NO depende de este campo sino de `fecha_inicio` (ver `vigente_de`): el fin real de un ciclo se deriva, no se persiste.', null=True),
        ),
        migrations.AddIndex(
            model_name='rutinaasignada',
            index=models.Index(fields=['alumno', '-fecha_inicio', '-id'], name='rutina_vigente_idx'),
        ),
    ]
