# Generated by Django 5.2.15 on 2026-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0013_reactivar_rutinas_archivadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaplantillaitem',
            name='repeticiones',
            field=models.CharField(blank=True, help_text='Notación libre: "10", "8-12", "AMRAP", etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutinaplantillaitem',
            name='series',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
