# Generated by Django 5.2.15 on 2026-09-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0014_items_a_completar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaplantilla',
            name='nivel',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rutinaplantilla',
            name='objetivo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
