# Generated by Django 5.2.15 on 2026-08-19 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_gimnasio_link_facebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suscripción push',
                'verbose_name_plural': 'suscripciones push',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('novedad_publicada', 'Novedad publicada'), ('pago_por_vencer', 'Pago por vencer'), ('pago_vencido', 'Pago vencido'), ('turno_proximo', 'Turno próximo')], max_length=20)),
                ('objeto_id', models.PositiveBigIntegerField()),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'recordatorio enviado',
                'verbose_name_plural': 'recordatorios enviados',
                'constraints': [models.UniqueConstraint(fields=('gimnasio', 'tipo', 'objeto_id'), name='recordatorio_unico_por_gimnasio_tipo_objeto')],
            },
        ),
    ]
