# Generated by Django 5.2.15 on 2026-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorioenviado',
            name='tipo',
            field=models.CharField(choices=[('novedad_publicada', 'Novedad publicada'), ('pago_por_vencer', 'Pago por vencer'), ('pago_vencido', 'Pago vencido'), ('turno_proximo', 'Turno próximo'), ('rutina_iniciada', 'Rutina iniciada')], max_length=20),
        ),
    ]
