# Generated by Django 5.2.15 on 2026-09-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_recordatorioenviado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorioenviado',
            name='tipo',
            field=models.CharField(choices=[('novedad_publicada', 'Novedad publicada'), ('pago_por_vencer', 'Pago por vencer'), ('pago_vencido', 'Pago vencido'), ('turno_proximo', 'Turno próximo'), ('rutina_iniciada', 'Rutina iniciada'), ('acceso_bloqueado', 'Acceso bloqueado')], max_length=20),
        ),
    ]
