# Generated by Django 5.2.15 on 2026-07-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=60)),
                ('titular', models.CharField(blank=True, max_length=80)),
                ('entidad', models.CharField(blank=True, max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'medio de cobro',
                'verbose_name_plural': 'medios de cobro',
                'ordering': ['alias'],
            },
        ),
    ]
