# Generated by Django 5.2.15 on 2026-08-19 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_mediocobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagomensual',
            name='comprobante',
            field=models.FileField(blank=True, upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
