# Generated by Django 5.2.15 on 2026-09-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_fecha_baja'),
        ('pagos', '0003_alter_pagomensual_comprobante'),
        ('tenants', '0008_gimnasio_link_facebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoMensual',
            new_name='Cuota',
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'cuota', 'verbose_name_plural': 'cuotas'},
        ),
    ]
