# Generated by Django 5.2.15 on 2026-07-07 23:03

import calendario.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alumno_perfil_alter_alumno_fecha_activacion'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('refresh_token', calendario.fields.EncryptedTextField(blank=True, default='')),
                ('access_token', calendario.fields.EncryptedTextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_calendar_summary', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_calendar', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'credencial de Google Calendar',
                'verbose_name_plural': 'credenciales de Google Calendar',
            },
        ),
        migrations.CreateModel(
            name='ReservaCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('sync_status', models.CharField(choices=[('ok', 'Sincronizado'), ('pending', 'Pendiente'), ('error', 'Error')], default='pending', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='turnos.reserva')),
            ],
            options={
                'verbose_name': 'evento de calendario',
                'verbose_name_plural': 'eventos de calendario',
            },
        ),
    ]
