# Generated by Django 5.2.15 on 2026-07-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('grupo_muscular', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('core', 'Core'), ('cardio', 'Cardio'), ('cuerpo_completo', 'Cuerpo completo')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('url_video', models.URLField(blank=True, help_text='Link de YouTube')),
                ('activo', models.BooleanField(default=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['nombre'],
            },
        ),
    ]
