# Generated by Django 5.2.15 on 2026-08-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('tenants', '0008_gimnasio_link_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('core', 'Core'), ('cardio', 'Cardio'), ('cuerpo_completo', 'Cuerpo completo')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CategoriaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60)),
                ('nombre_normalizado', models.CharField(editable=False, max_length=60)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor primero. A igual orden, alfabético.')),
                ('activo', models.BooleanField(default=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'categoría de ejercicio',
                'verbose_name_plural': 'categorías de ejercicio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios', to='ejercicios.categoriaejercicio', verbose_name='categoría'),
        ),
        migrations.AddConstraint(
            model_name='categoriaejercicio',
            constraint=models.UniqueConstraint(fields=('gimnasio', 'nombre_normalizado'), name='categoria_unica_por_gimnasio'),
        ),
    ]
