# Generated by Django 5.2.15 on 2026-08-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_backfill_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='url_video',
            field=models.URLField(blank=True, help_text='Link de YouTube', max_length=500),
        ),
    ]
