# Generated by Django 5.2.15 on 2026-07-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='color_primario',
            field=models.CharField(blank=True, help_text='Hex, p.ej. #2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='color_secundario',
            field=models.CharField(blank=True, help_text='Hex, p.ej. #1e40af', max_length=7),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='contacto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='link_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='link_whatsapp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='texto_bienvenida',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
