# Generated by Django 5.2.15 on 2026-07-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='tipografia',
            field=models.CharField(choices=[('sistema', 'Predeterminada (del sistema)'), ('inter', 'Inter — moderna y neutra'), ('montserrat', 'Montserrat — deportiva, alto impacto'), ('poppins', 'Poppins — cálida y redondeada'), ('oswald', 'Oswald — condensada'), ('playfair', 'Playfair Display — serif clásica, premium')], default='sistema', help_text='Tipografía del panel y del portal del alumno.', max_length=20),
        ),
    ]
