# Generated by Django 5.2.15 on 2026-07-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_actividad_fisica_previa_and_more'),
        ('tenants', '0003_gimnasio_tipografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSuplantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('finalizada_en', models.DateTimeField(blank=True, help_text='Cuándo volvió a su cuenta. Queda en blanco si cerró la pestaña sin volver -- riesgo aceptado, ver ISSUES.md.', null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suplantaciones_recibidas', to='alumnos.alumno')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
                ('staff_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suplantaciones_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='staff que suplantó')),
            ],
            options={
                'verbose_name': 'registro de suplantación',
                'verbose_name_plural': 'registros de suplantación',
                'ordering': ['-creado'],
            },
        ),
    ]
