# Generated by Django 5.2.15 on 2026-08-13 04:20

from django.db import migrations, models


def normalizar_tipografia_legada(apps, schema_editor):
    """Sin clientes pagos todavía (PRODUCT.md): los valores viejos de
    `tipografia` (sistema/inter/montserrat/oswald/playfair) no existen en el
    catálogo nuevo y `TIPOGRAFIA_FUENTES[valor]` rompería con KeyError en el
    primer render de base.html para un gimnasio existente. AlterField no
    convierte datos por su cuenta -- normalizar a ciegas es seguro acá."""
    Gimnasio = apps.get_model("tenants", "Gimnasio")
    Gimnasio.objects.update(tipografia="plus_jakarta")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_registrosuplantacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gimnasio',
            name='color_primario',
        ),
        migrations.RemoveField(
            model_name='gimnasio',
            name='color_secundario',
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='paleta',
            field=models.CharField(choices=[('bosque', 'Bosque'), ('oceano', 'Océano'), ('arena', 'Arena'), ('pizarra', 'Pizarra')], default='bosque', help_text='Paleta de colores del panel y del portal del alumno.', max_length=20),
        ),
        migrations.AlterField(
            model_name='gimnasio',
            name='tipografia',
            field=models.CharField(choices=[('plus_jakarta', 'Plus Jakarta Sans — geométrica, moderna'), ('sora', 'Sora — técnica, alto contraste'), ('manrope', 'Manrope — cálida y legible'), ('outfit', 'Outfit — redondeada, amigable'), ('space_grotesk', 'Space Grotesk — editorial, con carácter')], default='plus_jakarta', help_text='Tipografía del panel y del portal del alumno.', max_length=20),
        ),
        migrations.RunPython(normalizar_tipografia_legada, migrations.RunPython.noop),
    ]
