# Generated by Django 5.2.15 on 2026-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_paleta_curada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='fondo_doodle',
            field=models.CharField(blank=True, choices=[('mancuernas', 'Mancuernas'), ('sogas', 'Sogas de battle rope'), ('discos', 'Discos apilados'), ('kettlebell', 'Kettlebells')], max_length=20),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='fondo_imagen',
            field=models.ImageField(blank=True, upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='fondo_tipo',
            field=models.CharField(choices=[('color', 'Paisaje de color'), ('imagen', 'Imagen propia'), ('doodle', 'Doodle temático')], default='color', help_text='Qué se ve detrás del contenido: paisaje de color, una imagen propia, o un doodle temático.', max_length=10),
        ),
    ]
