# Generated by Django 5.2.15 on 2026-08-16 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_gimnasio_fondo_doodle_gimnasio_fondo_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='dia_vencimiento_pago',
            field=models.PositiveSmallIntegerField(default=10, help_text='Día del mes hasta el cual el alumno puede pagar la cuota sin quedar atrasado. Tope en 28 para que el día exista en cualquier mes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día límite de pago mensual'),
        ),
    ]
