# Generated by Django 5.2.15 on 2026-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_gimnasio_dia_vencimiento_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='link_facebook',
            field=models.URLField(blank=True),
        ),
    ]
