# Generated by Django 5.2.15 on 2026-09-04 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_gimnasio_link_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='dias_tolerancia_pago',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Días que el alumno puede seguir viendo su rutina y reservando turnos después de que arranca un ciclo impago. Pasados esos días se le bloquean esas dos secciones hasta que el staff confirme el pago. Dejalo VACÍO para no bloquear a nadie.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Días de tolerancia antes de bloquear'),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='fecha_activacion_bloqueo',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gimnasio',
            name='dia_vencimiento_pago',
            field=models.PositiveSmallIntegerField(default=10, help_text='OBSOLETO desde la migración a cuotas por ciclo: el vencimiento ya no cae un día fijo del mes sino a los `dias_tolerancia_pago` del arranque del ciclo de cada alumno. Se deja la columna un release para que revertir el código alcance como vuelta atrás (mismo criterio que `Ejercicio.grupo_muscular`).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día límite de pago mensual (en desuso)'),
        ),
    ]
