# Generated by Django 5.2.15 on 2026-09-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_gimnasio_dias_tolerancia_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='tipo_publico',
            field=models.CharField(choices=[('mixto', 'Mixto'), ('mujeres', 'Solo mujeres'), ('hombres', 'Solo hombres')], default='mixto', help_text='En un gimnasio de un solo género no se le pregunta el sexo a cada alumno (se completa solo) y el panel muestra la composición del padrón por edad en vez de por género.', max_length=10, verbose_name='Público del gimnasio'),
        ),
    ]
