# Generated by Django 5.2.15 on 2026-09-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_gimnasio_tipo_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='es_demo',
            field=models.BooleanField(default=False, help_text='Cuenta compartida de prueba: no puede cambiar su contraseña y sus datos se restauran automáticamente.', verbose_name='cuenta de demostración'),
        ),
    ]
