# Generated by Django 5.2.15 on 2026-09-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_gimnasio_es_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='exportacion_habilitada',
            field=models.BooleanField(default=False, help_text='Deja que el staff de este gimnasio descargue todos sus datos en CSV desde «Mi gimnasio». La cuenta de demostración exporta siempre.', verbose_name='exportación de datos habilitada'),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='exportacion_ultima_descarga',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='última exportación de datos'),
        ),
    ]
