# Generated by Django 5.2.15 on 2026-07-28 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('plantillas', 'Plantillas de rutina'), ('biblioteca', 'Biblioteca de ejercicios')], max_length=12)),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('estado', models.CharField(choices=[('en_revision', 'Pendiente de revisión'), ('confirmada', 'Confirmada'), ('descartada', 'Descartada')], default='en_revision', max_length=12)),
                ('resultado', models.JSONField()),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'importación',
                'verbose_name_plural': 'importaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
