# Generated by Django 5.2.15 on 2026-07-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_perfil_alter_alumno_fecha_activacion'),
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_leidas', to='alumnos.alumno')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='novedades.novedad')),
            ],
            options={
                'verbose_name': 'novedad leída',
                'verbose_name_plural': 'novedades leídas',
                'unique_together': {('novedad', 'alumno')},
            },
        ),
    ]
