# Generated by Django 5.2.15 on 2026-07-07 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_perfil_alter_alumno_fecha_activacion'),
        ('novedades', '0002_novedadleida'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_personales', to='alumnos.alumno'),
        ),
    ]
