# Generated by Django 5.2.15 on 2026-07-06 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alumno_perfil_alter_alumno_fecha_activacion'),
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('duracion_minutos', models.PositiveSmallIntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '60 minutos'), (75, '75 minutos'), (90, '90 minutos'), (105, '105 minutos'), (120, '120 minutos'), (135, '135 minutos'), (150, '150 minutos'), (165, '165 minutos'), (180, '180 minutos')], default=60)),
                ('vacantes_default', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'configuración de turnos',
                'verbose_name_plural': 'configuraciones de turnos',
                'constraints': [models.UniqueConstraint(fields=('gimnasio',), name='config_turnos_unica_por_gimnasio')],
            },
        ),
        migrations.CreateModel(
            name='CupoExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('vacantes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'excepción de cupo',
                'verbose_name_plural': 'excepciones de cupo',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('gimnasio', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'horario de atención',
                'verbose_name_plural': 'horarios de atención',
                'ordering': ['dia_semana', 'hora_desde'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_desde__lt', models.F('hora_hasta'))), name='horario_desde_antes_de_hasta')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='alumnos.alumno')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.gimnasio', verbose_name='gimnasio')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['gimnasio', 'fecha'], name='turnos_rese_gimnasi_f1ed86_idx')],
                'unique_together': {('gimnasio', 'alumno', 'fecha', 'hora_inicio')},
            },
        ),
    ]
