# Generated by Django 5.2.15 on 2026-07-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('tenants', '0002_gimnasio_color_primario_gimnasio_color_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='perfil',
            field=models.OneToOneField(blank=True, help_text='Login del alumno (usuario/contraseña asignados por el staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumno', to='tenants.perfil'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_activacion',
            field=models.DateTimeField(blank=True, help_text='Cuándo entró por primera vez con su usuario/contraseña (Fase 3).', null=True),
        ),
    ]
