# Generated by Django 5.2.15 on 2026-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_perfil_alter_alumno_fecha_activacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='actividad_fisica_previa',
            field=models.BooleanField(default=False, help_text='¿Hacía actividad física antes de anotarse?'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='deportes_practica',
            field=models.CharField(blank=True, help_text='Qué deporte(s) practica, o "ninguno". Texto libre: no amerita un catálogo cerrado como sí lo tiene grupo_muscular.', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='discapacidad_detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='enfermedad_cronica_detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='frecuencia_actividad_previa',
            field=models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('varias_por_semana', 'Varias veces por semana'), ('una_por_semana', 'Una vez por semana'), ('ocasional', 'Ocasional')], help_text='Solo si hacía actividad física antes.', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_decir', 'Prefiere no decir')], max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tiene_discapacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tiene_enfermedad_cronica',
            field=models.BooleanField(default=False),
        ),
    ]
