# Generated by Django 5.2.15 on 2026-09-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_actividad_fisica_previa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_baja',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
