# Generated by Django 5.2.15 on 2026-09-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_inicio_ciclo',
            field=models.DateField(blank=True, help_text='Día a partir del cual se cuentan los ciclos de cobro. Se completa solo con la fecha de la primera rutina asignada; corregilo solo si el alumno empezó a entrenar otro día.', null=True, verbose_name='Inicio del ciclo de pago'),
        ),
    ]
