# Generated by Django 5.2.15 on 2026-09-22 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0013_gimnasio_facturacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateField(help_text='El día en que entró la plata.', verbose_name='fecha de pago')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='monto en USD')),
                ('monto_ars', models.DecimalField(blank=True, decimal_places=2, help_text='Lo que de verdad se cobró. Opcional si no hay cotización.', max_digits=12, null=True, verbose_name='monto en pesos')),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=2, help_text='Dólar MEP (venta) del día del pago.', max_digits=10, null=True, verbose_name='tipo de cambio')),
                ('alumnos_activos', models.PositiveIntegerField(help_text='Cuántos tenía el gimnasio al cobrarle: justifica el precio.', verbose_name='alumnos activos')),
                ('periodo_desde', models.DateField(verbose_name='período desde')),
                ('periodo_hasta', models.DateField(verbose_name='período hasta (inclusive)')),
                ('notas', models.TextField(blank=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_plataforma', to='tenants.gimnasio')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_plataforma_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'pago de plataforma',
                'verbose_name_plural': 'pagos de plataforma',
                'ordering': ['-periodo_hasta', '-id'],
                'indexes': [models.Index(fields=['gimnasio', 'periodo_hasta'], name='pago_plat_gim_hasta_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('periodo_hasta__gte', models.F('periodo_desde'))), name='pago_plataforma_periodo_no_invertido')],
            },
        ),
    ]
