# Generated by Django 5.2.15 on 2026-09-22 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        ('tenants', '0013_gimnasio_facturacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagoplataforma',
            constraint=models.UniqueConstraint(fields=('gimnasio', 'periodo_desde'), name='pago_plataforma_un_periodo_por_gimnasio'),
        ),
    ]
