# Generated by Django 5.2.15 on 2026-09-22 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Crea la tabla de días de uso. Puramente aditiva, sin migración de datos.

    No se puede reconstruir el pasado: `User.last_login` guarda un solo
    instante por usuario, así que no hay de dónde sacar qué días entró antes
    del deploy. La tabla arranca vacía y el panel muestra «nunca» hasta que
    cada gimnasio entre por primera vez -- que es lo honesto, y no un
    histórico inventado a partir del último ingreso.
    """

    dependencies = [
        ('plataforma', '0002_pago_un_periodo_por_gimnasio'),
        ('tenants', '0014_gimnasio_estado_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('staff', 'Staff'), ('alumno', 'Alumno')], max_length=10)),
                ('fecha', models.DateField(help_text='Día LOCAL (America/Argentina/Buenos_Aires) en que entró.')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='tenants.gimnasio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_diaria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'día de actividad',
                'verbose_name_plural': 'días de actividad',
                'ordering': ['-fecha', 'usuario_id'],
                'indexes': [models.Index(fields=['gimnasio', 'fecha'], name='actividad_gim_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='actividad_un_dia_por_usuario')],
            },
        ),
    ]
