"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15, luego adaptado
del esqueleto reutilizable de ~/gestor-pedidos (ver REUSO.md).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga .env si existe (dev local). En producción las variables las pone la
# plataforma (Render) directamente en el entorno; load_dotenv no pisa las que
# ya estén seteadas.
load_dotenv(BASE_DIR / ".env")


def _env_bool(nombre, default):
    """Lee un booleano de entorno de forma tolerante ("1"/"true"/"yes"/"on")."""
    return os.environ.get(nombre, str(default)).lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY: en producción DEBE venir de la variable de entorno
# DJANGO_SECRET_KEY. El fallback `django-insecure-…` es SÓLO para desarrollo
# local y nunca debe usarse desplegado (un secret filtrado permite forjar
# sesiones/CSRF de todos los tenants).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-r$(4c96gd8=8@w2h2ec3grw1knf9k9v2u9v4x1)q9zg8k4z(vw",
)

# DEBUG arranca en True para desarrollo; en producción se apaga vía entorno.
DEBUG = _env_bool("DJANGO_DEBUG", True)

# Hosts permitidos desde entorno (CSV). Con DEBUG=True Django ya habilita
# localhost/127.0.0.1; en producción hay que setear DJANGO_ALLOWED_HOSTS.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto. Orden por dependencia:
    #   core    -> abstracciones (sin tablas)
    #   tenants -> Gimnasio / Perfil (núcleo multi-tenant)
    #   (Fase 1 agrega la app de dominio: alumnos, rutinas, pagos, novedades)
    'core',
    'tenants',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Assets propios del proyecto (CSS/JS/fuentes), no atados a una app concreta.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autenticación: dónde mandar a login y a dónde volver.
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"


# Logging: canal de auditoría para fallas/problemas en runtime. Consola
# siempre; archivo rotado en logs/app.log para poder revisar después de que
# pasó algo (Render también captura stdout, pero el archivo local ayuda en
# dev y sirve de referencia para el mismo patrón en producción).
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "app.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        # Excepciones no manejadas en requests (500s): quedan en el archivo,
        # no solo en la consola efímera del servidor.
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Endurecimiento mínimo para producción. Se activa solo con DEBUG apagado para
# no entorpecer el desarrollo local (HTTP, sin TLS). Cookies sobre HTTPS, HSTS
# y redirección a SSL; el header de proxy asume despliegue detrás de un
# balanceador que termina TLS (Render).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
