"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15, luego adaptado
del esqueleto reutilizable de ~/gestor-pedidos (ver REUSO.md).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga .env si existe (dev local). En producción las variables las pone la
# plataforma (Render) directamente en el entorno; load_dotenv no pisa las que
# ya estén seteadas.
load_dotenv(BASE_DIR / ".env")


def _env_bool(nombre, default):
    """Lee un booleano de entorno de forma tolerante ("1"/"true"/"yes"/"on")."""
    return os.environ.get(nombre, str(default)).lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY: en producción DEBE venir de la variable de entorno
# DJANGO_SECRET_KEY. El fallback `django-insecure-…` es SÓLO para desarrollo
# local y nunca debe usarse desplegado (un secret filtrado permite forjar
# sesiones/CSRF de todos los tenants).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-r$(4c96gd8=8@w2h2ec3grw1knf9k9v2u9v4x1)q9zg8k4z(vw",
)

# DEBUG arranca en True para desarrollo; en producción se apaga vía entorno.
DEBUG = _env_bool("DJANGO_DEBUG", True)

# Hosts permitidos desde entorno (CSV). Con DEBUG=True Django ya habilita
# localhost/127.0.0.1; en producción hay que setear DJANGO_ALLOWED_HOSTS.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto. Orden por dependencia:
    #   core       -> abstracciones (sin tablas)
    #   tenants    -> Gimnasio / Perfil (núcleo multi-tenant)
    #   ejercicios -> Ejercicio (sin dependencias de dominio)
    #   alumnos    -> Alumno (sin dependencias de dominio)
    #   rutinas    -> RutinaPlantilla/Item, RutinaAsignada/Item (FK a ejercicios y alumnos)
    #   pagos      -> PagoMensual (FK a alumnos)
    #   novedades  -> Novedad (sin dependencias de dominio)
    #   turnos     -> ConfiguracionTurnos/HorarioAtencion/CupoExcepcion/Reserva (FK a alumnos)
    'core',
    'tenants',
    'ejercicios',
    'alumnos',
    'rutinas',
    'pagos',
    'novedades',
    'turnos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los estáticos directamente desde el proceso Django en
    # Render (sin Nginx/CDN aparte) -- va justo después de SecurityMiddleware
    # por indicación de la propia documentación de WhiteNoise.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite en dev (sin DATABASE_URL seteado); Postgres en producción (Render la
# inyecta automáticamente vía Blueprint -- ver render.yaml). `conn_max_age`
# reusa conexiones entre requests (evita el costo de abrir una nueva conexión
# TCP+TLS a Postgres en cada request, importante en un plan free con recursos
# limitados). `ssl_require=not DEBUG`: Postgres de Render exige TLS.
if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(conn_max_age=600, ssl_require=not DEBUG)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Hashing de contraseñas: PBKDF2 (el default de Django) es lento a propósito
# (resiste fuerza bruta en producción) -- del orden de cientos de ms por hash.
# La suite crea decenas de usuarios (`create_user`) y hace más de cien
# `client.login()`, cada uno disparando ese hash; con `manage.py test` corriendo,
# se cambia a MD5 (inseguro, pero acá no importa) y baja la mayor parte del
# tiempo de la suite sin tocar el hasher real de producción/dev.
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Assets propios del proyecto (CSS/JS/fuentes), no atados a una app concreta.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Destino de `collectstatic` en producción (WhiteNoise sirve desde acá; en
# dev no se usa, Django sirve directo desde STATICFILES_DIRS).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (uploads de usuario: logo del gimnasio, comprobantes de pago).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# `staticfiles`: WhiteNoise con manifest + compresión SOLO fuera de DEBUG.
# El manifest lo genera `collectstatic` en el build de Render; en dev/tests
# no se corre `collectstatic`, así que exigir el manifest ahí rompe el
# `{% static %}` de cada template (no encuentra la entrada). En dev, Django
# ya sirve estáticos directo desde STATICFILES_DIRS sin manifest.
#
# `default` (media): FileSystemStorage en dev. En producción, si están
# seteadas las credenciales de R2, cambia a S3Storage (R2 es compatible con
# S3) SIN tocar los campos `ImageField`/`FileField` de los modelos — el
# filesystem de Render es efímero, nunca debe recibir un upload real.
STORAGES = {
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Las 4 variables de R2 son todo-o-nada: si se seteó alguna pero no las
# otras (p.ej. se completó a mano en el dashboard de Render de una en una),
# preferimos fallar fuerte y claro al arrancar en vez de un KeyError críptico
# más abajo -- o peor, silenciosamente quedar en FileSystemStorage.
_R2_VARS = ["R2_BUCKET_NAME", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_ENDPOINT_URL"]
_r2_seteadas = [v for v in _R2_VARS if os.environ.get(v)]

if _r2_seteadas and len(_r2_seteadas) < len(_R2_VARS):
    _r2_faltantes = ", ".join(v for v in _R2_VARS if v not in _r2_seteadas)
    raise ImproperlyConfigured(
        f"Configuración de R2 incompleta: falta(n) {_r2_faltantes}. "
        "Las 4 variables R2_* deben estar todas seteadas (o ninguna, para "
        "usar FileSystemStorage local) -- ver .env.example."
    )

if _r2_seteadas:
    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}
    AWS_STORAGE_BUCKET_NAME = os.environ["R2_BUCKET_NAME"]
    AWS_ACCESS_KEY_ID = os.environ["R2_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["R2_SECRET_ACCESS_KEY"]
    AWS_S3_ENDPOINT_URL = os.environ["R2_ENDPOINT_URL"]
    AWS_S3_REGION_NAME = "auto"
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_DEFAULT_ACL = None
    # `Gimnasio.logo`/`PagoMensual.comprobante` no tienen namespacing por
    # gimnasio en el nombre de archivo -- S3Storage sobreescribe por default
    # ante una colisión de nombre (a diferencia de FileSystemStorage, que
    # auto-renombra). Sin esto, dos gimnasios subiendo un "logo.png" pisarían
    # el archivo del otro en el mismo bucket compartido.
    AWS_S3_FILE_OVERWRITE = False
    # El bucket queda privado; las URLs que Django genera van firmadas
    # (query-string) y expiran -- comprobantes de pago son datos sensibles,
    # no tiene sentido que sean públicos aunque el logo sí podría serlo.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autenticación: dónde mandar a login y a dónde volver.
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"


# Logging: canal de auditoría para fallas/problemas en runtime. Consola
# siempre; archivo rotado en logs/app.log para poder revisar después de que
# pasó algo (Render también captura stdout, pero el archivo local ayuda en
# dev y sirve de referencia para el mismo patrón en producción).
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "app.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        # Excepciones no manejadas en requests (500s): quedan en el archivo,
        # no solo en la consola efímera del servidor.
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Orígenes de confianza para CSRF (Django exige esquema+host completo, a
# diferencia de ALLOWED_HOSTS que solo pide el hostname). En Render:
# https://<nombre-del-servicio>.onrender.com, o el dominio propio si se
# configura uno más adelante.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Endurecimiento mínimo para producción. Se activa solo con DEBUG apagado para
# no entorpecer el desarrollo local (HTTP, sin TLS). Cookies sobre HTTPS, HSTS
# y redirección a SSL; el header de proxy asume despliegue detrás de un
# balanceador que termina TLS (Render).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
