"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15, luego adaptado
del esqueleto reutilizable de ~/gestor-pedidos (ver REUSO.md).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import date
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from config.db import database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga .env si existe (dev local). En producción las variables las pone la
# plataforma (Render) directamente en el entorno; load_dotenv no pisa las que
# ya estén seteadas.
load_dotenv(BASE_DIR / ".env")


def _env_bool(nombre, default):
    """Lee un booleano de entorno de forma tolerante ("1"/"true"/"yes"/"on")."""
    return os.environ.get(nombre, str(default)).lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY: en producción DEBE venir de la variable de entorno
# DJANGO_SECRET_KEY. El fallback `django-insecure-…` es SÓLO para desarrollo
# local y nunca debe usarse desplegado (un secret filtrado permite forjar
# sesiones/CSRF de todos los tenants).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-r$(4c96gd8=8@w2h2ec3grw1knf9k9v2u9v4x1)q9zg8k4z(vw",
)

# DEBUG arranca en True para desarrollo; en producción se apaga vía entorno.
DEBUG = _env_bool("DJANGO_DEBUG", True)

# Hosts permitidos desde entorno (CSV). Con DEBUG=True Django ya habilita
# localhost/127.0.0.1; en producción hay que setear DJANGO_ALLOWED_HOSTS.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto. Orden por dependencia:
    #   core       -> abstracciones (sin tablas)
    #   tenants    -> Gimnasio / Perfil (núcleo multi-tenant)
    #   ejercicios -> Ejercicio (sin dependencias de dominio)
    #   alumnos    -> Alumno (sin dependencias de dominio)
    #   rutinas    -> RutinaPlantilla/Item, RutinaAsignada/Item (FK a ejercicios y alumnos)
    #   importaciones -> Importacion (FK a gymnastasio, usuario)
    #   pagos      -> PagoMensual (FK a alumnos)
    #   novedades  -> Novedad (sin dependencias de dominio)
    #   turnos     -> ConfiguracionTurnos/HorarioAtencion/CupoExcepcion/Reserva (FK a alumnos)
    #   calendario -> integración opcional con Google Calendar (FK a alumnos/turnos)
    #   notificaciones -> manifest/SW/push (FK a Gimnasio/Perfil, lee
    #                     Novedad/RutinaAsignada/Reserva/PagoMensual) -- depende
    #                     de todo el dominio, va última
    'core',
    'tenants',
    'ejercicios',
    'alumnos',
    'rutinas',
    'importaciones',
    'pagos',
    'novedades',
    'turnos',
    'calendario',
    'notificaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los estáticos directamente desde el proceso Django en
    # Render (sin Nginx/CDN aparte) -- va justo después de SecurityMiddleware
    # por indicación de la propia documentación de WhiteNoise.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Corta una suplantación vencida ("entrar como este alumno"). Va después
    # de AuthenticationMiddleware porque necesita `request.user` para
    # revalidar el gimnasio. Es el único control del proyecto que exige
    # evaluarse en CADA request y por eso no vive en un mixin -- ver el
    # docstring de tenants/middleware.py.
    'tenants.middleware.ExpirarSuplantacionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notificaciones.context_processors.vapid_public_key',
                'tenants.context_processors.google_staff_login_disponible',
                'tenants.context_processors.password_reset_disponible',
                'tenants.context_processors.tour_onboarding_disponible',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite en dev (sin DATABASE_URL seteada); Postgres en producción (Neon -- la
# URL se carga a mano en el dashboard de Render, ver render.yaml). La lógica
# vive en `config/db.py` para poder testearla sin recargar settings con otro
# entorno -- ver `config/tests.py`.
DATABASES = {
    "default": database_config(os.environ.get("DATABASE_URL"), DEBUG, BASE_DIR)
}


# Hashing de contraseñas: PBKDF2 (el default de Django) es lento a propósito
# (resiste fuerza bruta en producción) -- del orden de cientos de ms por hash.
# La suite crea decenas de usuarios (`create_user`) y hace más de cien
# `client.login()`, cada uno disparando ese hash; con `manage.py test` corriendo,
# se cambia a MD5 (inseguro, pero acá no importa) y baja la mayor parte del
# tiempo de la suite sin tocar el hasher real de producción/dev.
# Se calcula una sola vez y se reusa más abajo (storage de media): la suite
# tiene que quedar aislada de todo servicio externo, no solo acelerada.
TESTING = "test" in sys.argv

if TESTING:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Assets propios del proyecto (CSS/JS/fuentes), no atados a una app concreta.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Destino de `collectstatic` en producción (WhiteNoise sirve desde acá; en
# dev no se usa, Django sirve directo desde STATICFILES_DIRS).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (uploads de usuario: logo del gimnasio, comprobantes de pago).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# `staticfiles`: WhiteNoise con manifest + compresión SOLO fuera de DEBUG.
# El manifest lo genera `collectstatic` en el build de Render; en dev/tests
# no se corre `collectstatic`, así que exigir el manifest ahí rompe el
# `{% static %}` de cada template (no encuentra la entrada). En dev, Django
# ya sirve estáticos directo desde STATICFILES_DIRS sin manifest.
#
# `default` (media): FileSystemStorage en dev. En producción, si están
# seteadas las credenciales de R2, cambia a S3Storage (R2 es compatible con
# S3) SIN tocar los campos `ImageField`/`FileField` de los modelos — el
# filesystem de Render es efímero, nunca debe recibir un upload real.
#
# En TESTS va `InMemoryStorage`, y eso NO es una optimización: como el `.env`
# de desarrollo tiene las 4 `R2_*`, sin este caso especial la suite escribía
# al bucket REAL de producción. `importaciones/tests.py` sube `.xlsx` de
# verdad, así que cada corrida dejaba ~20 archivos huérfanos en
# `app-gim-media/importaciones/` (se habían acumulado 816 antes de detectarlo,
# ver ISSUES.md 2026-07-30). En memoria no toca ni la red ni el disco.
STORAGES = {
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
    "default": {
        "BACKEND": (
            "django.core.files.storage.InMemoryStorage"
            if TESTING
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
}

# Varias integraciones opcionales de este archivo (R2, Google Calendar,
# login con Google, email) comparten el mismo criterio todo-o-nada: si se
# seteó alguna variable del grupo pero no las otras (p.ej. se completó a
# mano en el dashboard de Render de una en una), preferimos fallar fuerte y
# claro al arrancar -- en vez de un KeyError críptico más abajo, o peor,
# quedar silenciosamente en el modo degradado. Devuelve True solo si TODAS
# las variables están seteadas, False si NINGUNA lo está.
def _bandera_todo_o_nada(nombres, etiqueta, degradacion):
    seteadas = [v for v in nombres if os.environ.get(v)]
    if seteadas and len(seteadas) < len(nombres):
        faltantes = ", ".join(v for v in nombres if v not in seteadas)
        raise ImproperlyConfigured(
            f"Configuración de {etiqueta} incompleta: falta(n) {faltantes}. "
            f"Las {len(nombres)} variables deben estar todas seteadas "
            f"(o ninguna, {degradacion}) -- ver .env.example."
        )
    return len(seteadas) == len(nombres)


R2_ENABLED = _bandera_todo_o_nada(
    ["R2_BUCKET_NAME", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_ENDPOINT_URL"],
    "R2",
    "para usar FileSystemStorage local",
)

# `not TESTING`: la validación de arriba sí corre siempre (una config parcial
# es un error de entorno en cualquier contexto), pero el backend real nunca se
# activa en la suite -- ver el comentario de STORAGES.
if R2_ENABLED and not TESTING:
    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}
    AWS_STORAGE_BUCKET_NAME = os.environ["R2_BUCKET_NAME"]
    AWS_ACCESS_KEY_ID = os.environ["R2_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["R2_SECRET_ACCESS_KEY"]
    AWS_S3_ENDPOINT_URL = os.environ["R2_ENDPOINT_URL"]
    AWS_S3_REGION_NAME = "auto"
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_DEFAULT_ACL = None
    # `Gimnasio.logo`/`PagoMensual.comprobante` no tienen namespacing por
    # gimnasio en el nombre de archivo -- S3Storage sobreescribe por default
    # ante una colisión de nombre (a diferencia de FileSystemStorage, que
    # auto-renombra). Sin esto, dos gimnasios subiendo un "logo.png" pisarían
    # el archivo del otro en el mismo bucket compartido.
    AWS_S3_FILE_OVERWRITE = False
    # El bucket queda privado; las URLs que Django genera van firmadas
    # (query-string) y expiran -- comprobantes de pago son datos sensibles,
    # no tiene sentido que sean públicos aunque el logo sí podría serlo.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600


# Parte C: integración opcional con Google Calendar (OAuth por alumno).
# Mismo criterio todo-o-nada que R2: si la integración está configurada, las 4
# variables deben estar; si no hay ninguna, la app degrada al deep-link actual
# ("Agregar a Google Calendar") sin tocar nada. Ver `calendario.services`.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get("GOOGLE_OAUTH_REDIRECT_URI", "")
GOOGLE_TOKEN_ENCRYPTION_KEY = os.environ.get("GOOGLE_TOKEN_ENCRYPTION_KEY", "")

# Scope mínimo: `calendar.app.created` NO da acceso al calendario principal del
# alumno -- solo permite crear calendarios secundarios y gestionar eventos en
# ellos (por eso la app crea un calendario "Turnos de {gimnasio}"). Ver
# https://developers.google.com/workspace/calendar/api/auth
GOOGLE_CALENDAR_SCOPES = ["https://www.googleapis.com/auth/calendar.app.created"]

GOOGLE_CALENDAR_ENABLED = _bandera_todo_o_nada(
    [
        "GOOGLE_OAUTH_CLIENT_ID",
        "GOOGLE_OAUTH_CLIENT_SECRET",
        "GOOGLE_OAUTH_REDIRECT_URI",
        "GOOGLE_TOKEN_ENCRYPTION_KEY",
    ],
    "Google Calendar",
    "para degradar al deep-link",
)

# Frente C: login con Google para staff/dueño (coexiste con usuario+contraseña,
# no lo reemplaza -- ver ISSUES.md [2026-07-29]). Reusa el MISMO Client
# ID/Secret de Google Cloud que Calendar (un OAuth client admite varias
# "Authorized redirect URIs"); no hace falta GOOGLE_TOKEN_ENCRYPTION_KEY acá
# porque este flujo no persiste tokens, solo verifica el email del staff en
# el momento. Chequeo todo-o-nada independiente y paralelo al de Calendar
# (ver `tenants.google_login`) -- CLIENT_ID/CLIENT_SECRET quedan compartidas
# entre los dos chequeos a propósito: si algún día se arma un entorno nuevo
# con SOLO estas 3 variables (sin las 4 de Calendar), el chequeo de arriba
# va a reventar en el arranque -- hace falta setear las 4 de Calendar igual,
# aunque no se use.
GOOGLE_LOGIN_REDIRECT_URI = os.environ.get("GOOGLE_LOGIN_REDIRECT_URI", "")
GOOGLE_LOGIN_SCOPES = ["openid", "email"]

GOOGLE_STAFF_LOGIN_ENABLED = _bandera_todo_o_nada(
    ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET", "GOOGLE_LOGIN_REDIRECT_URI"],
    "login con Google",
    "para que solo quede el login por contraseña",
)

# "Olvidé mi contraseña" -- reset por email, SOLO para staff/dueño (ver
# tenants.forms.ResetPasswordStaffForm: el reset de un alumno queda afuera
# aunque su identificador sea un email, decisión de producto explícita).
# Resend vía el `EMAIL_BACKEND` SMTP que Django ya trae -- sin
# django-anymail ni el paquete `resend`, mismo criterio de "reusar antes
# que agregar dependencias" que el login con Google. `EMAIL_PORT`/
# `EMAIL_USE_TLS` son constantes (el submission port TLS de Resend), no
# variables de entorno: no hay motivo real para que varíen entre entornos.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "")
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Bandera que consumen tenants/context_processors.py y login.html para
# mostrar u ocultar "¿Olvidaste tu contraseña?". Sin configurar, el
# EMAIL_BACKEND cae al de consola (nunca rompe nada, solo no manda mails
# reales) -- coherente con que el link quede oculto en ese caso, para no
# ofrecer un flujo que no entrega nada.
PASSWORD_RESET_ENABLED = _bandera_todo_o_nada(
    ["EMAIL_HOST", "EMAIL_HOST_USER", "EMAIL_HOST_PASSWORD", "DEFAULT_FROM_EMAIL"],
    "email",
    "para que 'olvidé mi contraseña' quede oculto",
)
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if PASSWORD_RESET_ENABLED
    else "django.core.mail.backends.console.EmailBackend"
)


# PWA / Web Push (app `notificaciones`). Mismo criterio todo-o-nada que
# GOOGLE_*/R2_*: sin las 3 variables, `notificaciones.services` se vuelve
# no-op -- la PWA sigue siendo instalable (manifest/SW no dependen de esto),
# solo no se mandan notificaciones. Generar el par de claves una sola vez con
# `vapid --gen` + `vapid --applicationServerKey` (comando de `py-vapid`,
# dependencia transitiva de `pywebpush`); nunca commitear los .pem.
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")
VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_ADMIN_EMAIL = os.environ.get("VAPID_ADMIN_EMAIL", "")

# Forzado a False en la suite de tests independientemente de las env vars:
# mismo criterio ya usado para R2 (ver STORAGES más abajo) -- `manage.py
# test` no debe salir a la red por ningún motivo, aunque algún test olvide
# mockear `notificaciones.services._enviar`.
PUSH_ENABLED = (
    _bandera_todo_o_nada(
        ["VAPID_PRIVATE_KEY", "VAPID_PUBLIC_KEY", "VAPID_ADMIN_EMAIL"],
        "Web Push",
        "para que la app funcione sin push",
    )
    and not TESTING
)

# Tour de bienvenida para staff nuevo (notas dismissibles guiando los
# primeros pasos: logo, colores/fondo, importar ejercicios/rutinas). El
# progreso vive en localStorage (ver static/js/tour_onboarding.js), no en la
# base -- esta fecha es la única pieza server-side: sin ella no habría forma
# de distinguir un dueño nuevo de uno que ya usa la app hace meses (el
# navegador de ambos arranca sin la clave de localStorage seteada). Perfiles
# de staff creados antes de esta fecha nunca ven el tour.
TOUR_ONBOARDING_DESDE = date(2026, 8, 26)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autenticación: dónde mandar a login y a dónde volver.
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"


# Logging: canal de auditoría para fallas/problemas en runtime. Consola
# siempre; archivo rotado en logs/app.log para poder revisar después de que
# pasó algo (Render también captura stdout, pero el archivo local ayuda en
# dev y sirve de referencia para el mismo patrón en producción).
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "app.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        # Excepciones no manejadas en requests (500s): quedan en el archivo,
        # no solo en la consola efímera del servidor.
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Orígenes de confianza para CSRF (Django exige esquema+host completo, a
# diferencia de ALLOWED_HOSTS que solo pide el hostname). En Render:
# https://<nombre-del-servicio>.onrender.com, o el dominio propio si se
# configura uno más adelante.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Endurecimiento mínimo para producción. Se activa solo con DEBUG apagado para
# no entorpecer el desarrollo local (HTTP, sin TLS). Cookies sobre HTTPS, HSTS
# y redirección a SSL; el header de proxy asume despliegue detrás de un
# balanceador que termina TLS (Render).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
