# Generated by Django 5.2.15 on 2026-09-25 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0014_gimnasio_estado_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre_gimnasio', models.CharField(max_length=200, verbose_name='nombre del gimnasio')),
                ('email', models.EmailField(help_text='Se normaliza a minúsculas (mismo criterio que el alta).', max_length=255)),
                ('nombre_contacto', models.CharField(max_length=200, verbose_name='nombre de contacto')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='teléfono / WhatsApp')),
                ('cantidad_alumnos', models.PositiveIntegerField(blank=True, help_text='Orientativo: es lo que define el escalón de precio.', null=True, verbose_name='cantidad aproximada de alumnos')),
                ('anios_operando', models.CharField(blank=True, choices=[('menos_1', 'Menos de 1 año'), ('entre_1_3', 'Entre 1 y 3 años'), ('entre_3_10', 'Entre 3 y 10 años'), ('mas_10', 'Más de 10 años')], max_length=20)),
                ('tamano_staff', models.CharField(blank=True, choices=[('solo_yo', 'Solo yo'), ('entre_2_5', '2 a 5 personas'), ('entre_6_15', '6 a 15 personas'), ('mas_15', 'Más de 15 personas')], max_length=20)),
                ('banda_ingresos', models.CharField(blank=True, choices=[('no_dice', 'Prefiero no decirlo'), ('baja', 'Chica'), ('media', 'Mediana'), ('alta', 'Grande')], max_length=20)),
                ('formato_registros', models.CharField(blank=True, choices=[('papel', 'Papel / cuaderno'), ('excel', 'Excel o planilla'), ('whatsapp', 'WhatsApp / notas sueltas'), ('otra_app', 'Otra app'), ('nada', 'No llevo registro')], max_length=20)),
                ('profundidad_historia', models.CharField(blank=True, choices=[('sin_historia', 'Arranco de cero'), ('meses', 'Unos meses'), ('un_anio', 'Alrededor de un año'), ('varios_anios', 'Varios años')], max_length=20)),
                ('puede_compartir_archivos', models.CharField(blank=True, choices=[('si', 'Sí, tengo los datos a mano'), ('no', 'No'), ('no_se', 'No estoy seguro')], max_length=10)),
                ('comentario', models.TextField(blank=True, max_length=2000, verbose_name='comentario del interesado')),
                ('estado', models.CharField(choices=[('no_verificada', 'Sin verificar el email'), ('pendiente', 'Pendiente de revisión'), ('lista_espera', 'En lista de espera'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='no_verificada', max_length=20)),
                ('verificada_en', models.DateTimeField(blank=True, null=True)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_decision', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gimnasio_creado', models.ForeignKey(blank=True, help_text='Se llena al aprobar, cuando se acuña el tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.gimnasio')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAccesoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('proposito', models.CharField(choices=[('verificacion', 'Verificación de email')], default='verificacion', max_length=20)),
                ('expira', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='solicitudes.solicitudacceso')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('de_estado', models.CharField(blank=True, choices=[('no_verificada', 'Sin verificar el email'), ('pendiente', 'Pendiente de revisión'), ('lista_espera', 'En lista de espera'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], max_length=20)),
                ('a_estado', models.CharField(choices=[('no_verificada', 'Sin verificar el email'), ('pendiente', 'Pendiente de revisión'), ('lista_espera', 'En lista de espera'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, help_text='El superadmin que decidió; vacío si lo hizo el propio flujo (verificación, expiración).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='solicitudes.solicitudacceso')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitudacceso',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['no_verificada', 'pendiente', 'lista_espera'])), fields=('email',), name='una_solicitud_abierta_por_email'),
        ),
    ]
